"""newUpdates1

Revision ID: 02edbe62ed60
Revises: 8603b793cec8
Create Date: 2024-02-05 12:10:20.857878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02edbe62ed60'
down_revision = '8603b793cec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
