"""create fashion

Revision ID: 034af9a2a366
Revises: 
Create Date: 2023-08-31 16:35:45.790519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034af9a2a366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
