"""first migration

Revision ID: 292e108225ee
Revises: 034af9a2a366
Create Date: 2023-08-31 19:53:28.844901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292e108225ee'
down_revision = '034af9a2a366'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('profile')
    op.drop_table('admin')
    op.drop_table('superadmin')
    op.drop_table('cart')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'products_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'products_id')
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'carts', ['cart_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])
    op.add_column('reviews', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    op.add_column('sales', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'product_id')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'product_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'products', 'cart', ['cart_id'], ['id'])
    op.drop_column('products', 'image')
    op.add_column('orders', sa.Column('products_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'products', ['products_id'], ['id'])
    op.add_column('images', sa.Column('products_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'images', 'products', ['products_id'], ['id'])
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sales_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('superadmin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(), nullable=True),
    sa.Column('lname', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('contacts', sa.INTEGER(), nullable=True),
    sa.Column('profilepicture', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
