"""carts

Revision ID: 2ff56305b731
Revises: 22a650a47f5b
Create Date: 2024-02-01 10:19:14.108661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff56305b731'
down_revision = '22a650a47f5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['client_id'], ['id'])
    op.create_foreign_key(None, 'carts', 'products', ['product_id'], ['id'])
    op.drop_column('carts', 'productss')
    op.drop_column('carts', 'sales_id')
    op.drop_column('carts', 'customer_id')
    op.add_column('orders', sa.Column('name', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('password', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('userr', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['userr'], ['id'])
    op.add_column('sales', sa.Column('name', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('message', sa.String(), nullable=True))
    op.create_foreign_key(None, 'services', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('super_ad', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'superadmins', ['super_ad'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'super_ad')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'message')
    op.drop_column('services', 'user_id')
    op.drop_column('sales', 'amount')
    op.drop_column('sales', 'quantity')
    op.drop_column('sales', 'name')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'userr')
    op.drop_column('profile', 'password')
    op.drop_column('orders', 'name')
    op.add_column('carts', sa.Column('customer_id', sa.INTEGER(), nullable=True))
    op.add_column('carts', sa.Column('sales_id', sa.INTEGER(), nullable=True))
    op.add_column('carts', sa.Column('productss', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'sales', ['sales_id'], ['id'])
    # ### end Alembic commands ###
