"""Newdatabase6

Revision ID: 802eb759f4fb
Revises: 
Create Date: 2024-02-08 10:19:12.166250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802eb759f4fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
