"""second entry3

Revision ID: 9b126c867804
Revises: 2dca7fd37984
Create Date: 2023-09-06 10:39:59.778088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b126c867804'
down_revision = '2dca7fd37984'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
