"""Update Database

Revision ID: cac055d26853
Revises: 9b126c867804
Create Date: 2023-12-05 11:53:28.860895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac055d26853'
down_revision = '9b126c867804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('users', 'lname')
    op.drop_column('users', 'profilepicture')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'contacts')
    op.drop_column('users', 'fname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fname', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('contacts', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('profilepicture', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('lname', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
